name: CI
on:
 push:
   branches: [ master ]
 pull_request:
   branches: [ master ]
 workflow_dispatch:
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v2
      
      - name: Scripts
       
         
        run:
         docker build -t app .
         docker login --username shreyaasatish --password dckr_pat_nktKLHKujD106TWh6vaoK1a6kyw      
         docker tag app shreyaasatish/virtuproj
         docker push shreyaasatish/virtuproj
